### PR TITLE
Setup a docker image

### LINKED ISSUE #7: Make the application ready to be run on Docker
Create a docker image that can run the entire application via a container

### PR DESCRIPTION
**Pull request by eigengravy**
Dockerfile installs the dependencies and exposes port 3000

Closes #7

### CODE REVIEW

**Review by ananth243 — CHANGES_REQUESTED** [review]
Node versions are bound to change in the future so try the latest docker image and a [clean install](https://docs.npmjs.com/cli/v8/commands/npm-ci) should do the job.

**Comment by eigengravy** [comment]
Made the changes

**Review by ananth243 — APPROVED** [review]

**Comment by ananth243** [comment]
@riskycase looks good to me.

**Comment by riskycase** [comment]
Merging

**Pull request merged**
